M48
; DRILL file {KiCad 9.0.5} date 2026-08-11T20:09:24-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-11T20:09:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X77.25Y-13.11
X77.25Y-18.89
T2
X4.0Y-4.0
X4.0Y-96.0
X80.0Y-4.0
X80.0Y-96.0
M30
